apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 3306
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:14
          name: postgres
          volumeMounts:
            - name: persistent-storage
              mountPath: /var/lib/postgresql/data
          env:
            # Use secret in real usage
            - name: POSTGRES_USER
              value: dev
            - name: POSTGRES_PASSWORD
              value: dev
            - name: POSTGRES_DB
              value: code-challenge
          ports:
            - containerPort: 3306
              name: mysql
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
  # Volume Claim
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
