// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	model "github.com/duyquang6/quote-today/internal/model"
)

// QuoteRepository is an autogenerated mock type for the QuoteRepository type
type QuoteRepository struct {
	mock.Mock
}

// GetRandomQuote provides a mock function with given fields: ctx, tx
func (_m *QuoteRepository) GetRandomQuote(ctx context.Context, tx *gorm.DB) (model.Quote, error) {
	ret := _m.Called(ctx, tx)

	var r0 model.Quote
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB) model.Quote); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Get(0).(model.Quote)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *gorm.DB) error); ok {
		r1 = rf(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
