apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quote-today.fullname" . }}
  labels:
    {{- include "quote-today.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
    "helm.sh/hook-delete-policy": before-hook-creation
data:  
  DB_NAME: "code-challenge"
  DB_USER: "dev"
  DB_ADDRESS: "postgres:5432"
  LOG_MODE: "production"
  LOG_LEVEL: "INFO"
  GIN_MODE: "release"
